// src/quiz-vue/src/components/NavBar.vue
<script setup lang="ts">
const { availableLocales, locale } = useI18n()

// Menu
const showMenu = ref(false)

// Locale
const toggleLocales = () => {
  const locales = availableLocales
  locale.value = locales[(locales.indexOf(locale.value) + 1) % locales.length]
}
</script>

<template>
  <header>
    <div class="navbar rounded-box mb-2 bg-primary shadow-lg">
      <div class="md:hidden">
        <button class="btn-ghost btn-square btn" @click="showMenu = !showMenu">
          <i-tabler:menu-2 v-if="!showMenu" class="h-8 w-8" />
          <i-tabler:x v-else class="h-8 w-8" />
        </button>
      </div>

      <div class="navbar-start mx-2 px-2">
        <span class="text-lg font-bold">
          <RouterLink class="nav-btn" to="/"> Qüiz </RouterLink>
        </span>
      </div>

      <div class="navbar-center mx-2 px-2">
        <div class="hidden items-stretch md:flex">
          <RouterLink class="nav-btn" to="/">
            {{ $t('nav.home') }}
          </RouterLink>
          <RouterLink class="nav-btn" to="/about">
            {{ $t('nav.about') }}
          </RouterLink>
        </div>
      </div>

      <div class="navbar-end">
        <button class="btn-ghost btn-square btn" @click="toggleLocales">
          <i-tabler:language class="h-8 w-8" />
        </button>
      </div>
    </div>

    <ul
      v-if="showMenu"
      class="menu rounded-box bg-primary py-3 font-bold md:hidden"
    >
      <li>
        <RouterLink class="nav-btn" to="/" @click="showMenu = !showMenu">
          {{ $t('nav.home') }}
        </RouterLink>
      </li>
      <div class="divider mt-0 mb-0" />
      <li>
        <RouterLink class="nav-btn" to="/about" @click="showMenu = !showMenu">
          {{ $t('nav.about') }}
        </RouterLink>
      </li>
    </ul>
  </header>
</template>

<style scoped>
.nav-btn {
  @apply btn-ghost rounded-btn btn-sm btn;
}
</style>

// src/pokedex-sveltekit/src/components/NavBar.svelte
<script lang="ts">
  import { scale } from "svelte/transition";
  import { base } from "$app/paths";
  import { searchTerm as searchTermStore } from "../stores/search";
  import SearchIcon from "./icons/IconSearch.svelte";
  import HamburgerIcon from "./icons/IconHamburger.svelte";

  // Menu
  let showMenu = false;

  // Search
  let showSearchBar = false;
  export let searchTerm = "";
  $: $searchTermStore = searchTerm;
</script>

<div class="navbar rounded-box mb-2 bg-primary shadow-lg">
  <div class="md:hidden">
    <button on:click={() => (showMenu = !showMenu)} class="btn-ghost btn-square btn">
      <HamburgerIcon />
    </button>
  </div>

  <div class="navbar-start mx-2 px-2">
    <span class="text-lg font-bold">
      <a href="{base}/">Pokedex</a>
    </span>
  </div>

  <div class="navbar-center mx-2 px-2">
    <div class="flex hidden items-stretch md:flex">
      <a class="nav-btn" href="{base}/"> Home </a>
      <a class="nav-btn" href="{base}/about"> About </a>
    </div>
  </div>

  <div class="navbar-end">
    {#if showSearchBar}
      <div in:scale out:scale class="form-control text-neutral">
        <input
          type="text"
          placeholder="bulbasur"
          class="input-bordered input"
          bind:value={searchTerm}
        />
      </div>
    {/if}
    <button class="btn-ghost btn-square btn" on:click={() => (showSearchBar = !showSearchBar)}>
      <SearchIcon />
    </button>
  </div>
</div>

{#if showMenu}
  <div class="">
    <ul class="menu rounded-box bg-primary py-3 font-bold">
      <li><a href="{base}/">Home</a></li>
      <li><a href="{base}/about">About</a></li>
    </ul>
  </div>
{/if}

<style lang="postcss">
  .nav-btn {
    @apply btn-ghost rounded-btn btn-sm btn;
  }
</style>
