// src/pokedex/vue/src/pages/pokemon/[id].vue
<script setup lang="ts">
import type { Pokemon } from '../../types/Pokemon'

// Auto register for types is WIP
// <https://github.com/antfu/unplugin-auto-import/issues/61>

// `id` passed from vite-plugin-pages
// props passed has `string` type
const props = defineProps<{ id: string }>()

let pokemon_: Pokemon = $ref({
  id: 0,
  name: '',
  image: '',
  height: 0,
  weight: 0,
})

onMounted(async () => {
  const id = props.id
  const url = `https://pokeapi.co/api/v2/pokemon/${id}`
  const res = await fetch(url)
  const pokemonItem = await res.json()

  const pokemonResult = await {
    id: pokemonItem.id,
    name: pokemonItem.name,
    image: `https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/${
      pokemonItem.id + 1
    }.png`,
    height: pokemonItem.height,
    weight: pokemonItem.weight,
  }
  pokemon_ = pokemonResult
})
</script>

<template>
  <PokemonCard :pokemon="pokemon_" :is-detail-page="true" />
</template>

// src/pokedex-sveltekit/src/routes/pokemon/[id].svelte
<script context="module" lang="ts">
  import type { Pokemon } from "../../types/Pokemon";

  export async function load({ url }) {
    const id = url.params.id;
    const url_ = `https://pokeapi.co/api/v2/pokemon/${id}`;
    const res = await fetch(url_);
    const pokemon_ = await res.json();

    const pokemon = {
      id: pokemon_.id,
      name: pokemon_.name,
      image: `https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/${
        pokemon_.id + 1
      }.png`,
      height: pokemon_.height,
      weight: pokemon_.weight
    };
    return {
      props: {
        pokemon
      }
    };
  }
</script>

<script lang="ts">
  import PokemonCard from "../../components/PokemonCard.svelte";

  export let pokemon: Pokemon;
</script>

<PokemonCard {pokemon} endPage={true} />
