// src/pokedex-sveltekit/src/components/NavBar.svelte
<script lang="ts">
  import { scale } from "svelte/transition";
  import { base } from "$app/paths";
  import { searchTerm as searchTermStore } from "../stores/search";
  import SearchIcon from "./icons/IconSearch.svelte";
  import HamburgerIcon from "./icons/IconHamburger.svelte";

  // Menu
  let showMenu = false;

  // Search
  let showSearchBar = false;
  export let searchTerm = "";
  $: $searchTermStore = searchTerm;
</script>

<div class="navbar rounded-box mb-2 bg-primary shadow-lg">
  <div class="md:hidden">
    <button on:click={() => (showMenu = !showMenu)} class="btn-ghost btn-square btn">
      <HamburgerIcon />
    </button>
  </div>

  <div class="navbar-start mx-2 px-2">
    <span class="text-lg font-bold">
      <a href="{base}/">Pokedex</a>
    </span>
  </div>

  <div class="navbar-center mx-2 px-2">
    <div class="flex hidden items-stretch md:flex">
      <a class="nav-btn" href="{base}/"> Home </a>
      <a class="nav-btn" href="{base}/about"> About </a>
    </div>
  </div>

  <div class="navbar-end">
    {#if showSearchBar}
      <div in:scale out:scale class="form-control text-neutral">
        <input
          type="text"
          placeholder="bulbasur"
          class="input-bordered input"
          bind:value={searchTerm}
        />
      </div>
    {/if}
    <button class="btn-ghost btn-square btn" on:click={() => (showSearchBar = !showSearchBar)}>
      <SearchIcon />
    </button>
  </div>
</div>

{#if showMenu}
  <div class="">
    <ul class="menu rounded-box bg-primary py-3 font-bold">
      <li><a href="{base}/">Home</a></li>
      <li><a href="{base}/about">About</a></li>
    </ul>
  </div>
{/if}

<style lang="postcss">
  .nav-btn {
    @apply btn-ghost rounded-btn btn-sm btn;
  }
</style>

// src/pokedex/vue/src/components/NavBar.vue
<script setup lang="ts">
const { availableLocales, locale } = useI18n()

// Menu
const showMenu = ref(false)

// Search
const searchStore = useSearchStore()
const showSearchBar = ref(false)
const updateSearchTerm = debounce((e) => {
  searchStore.setSearchTerm(e.target.value)
}, 100)

// Locale
function toggleLocales() {
  const locales = availableLocales
  locale.value = locales[(locales.indexOf(locale.value) + 1) % locales.length]
}
</script>

<template>
  <div class="mb-2 shadow-lg navbar rounded-box bg-primary">
    <div class="md:hidden">
      <button class="btn btn-ghost btn-square" @click="showMenu = !showMenu">
        <i-tabler:menu-2 class="w-8 h-8" />
      </button>
    </div>

    <div class="px-2 mx-2 navbar-start">
      <span class="text-lg font-bold">
        <RouterLink class="nav-btn" to="/"> Pokédex </RouterLink>
      </span>
    </div>

    <div class="px-2 mx-2 navbar-center">
      <div class="hidden items-stretch md:flex">
        <RouterLink class="nav-btn" to="/">
          {{ $t('Home') }}
        </RouterLink>
        <RouterLink class="nav-btn" to="/about">
          {{ $t('About') }}
        </RouterLink>
      </div>
    </div>

    <div class="navbar-end">
      <div v-if="showSearchBar" class="form-control">
        <input
          type="text"
          placeholder="bulbasur"
          class="input input-bordered"
          @input="updateSearchTerm"
        >
      </div>
      <button
        class="btn btn-primary btn-square"
        @click="showSearchBar = !showSearchBar"
      >
        <i-tabler:search class="w-8 h-8" />
      </button>
      <button class="btn btn-primary btn-square" @click="toggleLocales">
        <i-tabler:language class="w-8 h-8" />
      </button>
    </div>
  </div>

  <ul
    v-if="showMenu"
    class="py-3 font-bold md:hidden menu rounded-box bg-primary"
  >
    <li>
      <RouterLink class="nav-btn" to="/">
        {{ $t('Home') }}
      </RouterLink>
    </li>
    <li>
      <RouterLink class="nav-btn" to="/about">
        {{ $t('About') }}
      </RouterLink>
    </li>
  </ul>
</template>

<style scoped>
.nav-btn {
  @apply btn-primary rounded-btn btn-sm btn;
}
</style>
